### ISSUE TITLE
Monochrome battery indicator.

### ISSUE THREAD

**Issue by Blast-City** [elementary/wingpanel-indicator-power#109]
Hi.

Is there a reason why the battery level indicator is not monochrome on all states like the rest of the wingpanel icons?

I'm sorry if this issue has been posted before.

**Comment by cassidyjames** [comment]
Indicators can use color to denote important states. For example, the notifications indicator has a red dot when there are new, unread notifications. The sound indicator turns orange when there's something making a sound while it's muted. And I believe the battery indicator has a red alert for a critically-low state, and a green fill for the fully-charged state (to let you know your device can be unplugged).

**Comment by Blast-City** [comment]
> Indicators can use color to denote important states. For example, the notifications indicator has a red dot when there are new, unread notifications. The sound indicator turns orange when there's something making a sound while it's muted. And I believe the battery indicator has a red alert for a critically-low state, and a green fill for the fully-charged state (to let you know your device can be unplugged).

Hi.

I thought about the notifications red dot, but because is something that you're suppose to click it, i disn't mention it.

I think that the 100% battery percentage would be a enough indicator that you can unplug the computer. When you unplugged the computer, it should show a fully charged monochrome icon because is the normal state (like the other icons)

The red alert makes sense to me, though, because the alert is suppose to be on the wingpanel just a small amount of time until you notice it and plug the power again.

Thanks.
