### ISSUE TITLE
Power mode option for good battery life

### ISSUE THREAD

**Issue by fivemoreminix** [elementary/wingpanel-indicator-power#132]
## Feature

I work on a pretty beefy MSI Workstation laptop, but I don't want the animations from Elementary, for example, when I want all the battery life I can get. This is a feature that has existed on Windows OS since (around) Windows 7. They also have other power options like "High performance" that disables lots of internal OS features to improve performance but I'm not sure that's necessary with Elementary because it is mostly slim.

This feature would be best implemented as a on/off button on the panel for the case of batteries. It should disable animations in the operating system and any other very minute details that could otherwise be prevented to save on battery.

**Alternatives considered**

I have turned my screen brightness down to the very limit I'm comfortable with and my keyboard brightness is completely off. Works great, but more could be done.

**Additional context**

![image](https://user-images.githubusercontent.com/13669835/75117180-d3cdf600-5634-11ea-8d68-45fc51904aa4.png)

**Comment by janxkoci** [comment]
FYI: Animations can be disabled in the **Switchboard** > **Accessibility**. Have you tried if it actually affects performance / battery life?

When I read the title, I actually thought about integrating something like `laptop-mode-tools` or similar tool (there is at least one other, but I don't remember it's name). I think the main problem with those is that they are not good for every hardware, so shipping them by default can be bad in some cases, I guess.

One other thing that the "power mode" could do is to pause AppCenter updates checking etc. And the code could be even reused for metered networks, when they get finally implemented :smiley:

**Comment by andirsun** [comment]
@janxkoci How about battery life mode in pop_os. The battery life mode use only the internal graphics and dont know how much other tweaks for improve the battery.

**Comment by janxkoci** [comment]
I have no experience with Pop_OS nor with secondary graphics, so I cannot comment on how that would work. I got the impression that some GPU & driver combinations require reboot when switching between GPUs, so there are probably limits to what can be provided in general OS UI and works for everyone.

**Comment by andirsun** [comment]
partially fixed here: https://github.com/elementary/switchboard-plug-power/pull/192
