### ISSUE TITLE
Power indicator always showing 100%

### ISSUE THREAD

**Issue by pepucho** [elementary/wingpanel-indicator-power#136]
The power indicator always shows 100% battery with or without the charger connected.
Using elementary OS 5.1.3 Hera with all the updates installed

**Comment by kvdz** [comment]
Hey, I am interested to work on this issue. Could you supply me more information?
Could you add screenshots here of what you are seeing?

Additional could you show me the information you get when entering the following commands in the terminal:
`upower -e`
and 
`upower -i <battery path>`

example :
```
kay@kay-XPS-15-9570:~$ upower -e
/org/freedesktop/UPower/devices/line_power_AC
/org/freedesktop/UPower/devices/battery_BAT0
/org/freedesktop/UPower/devices/tablet_wacom_battery_0
/org/freedesktop/UPower/devices/DisplayDevice
kay@kay-XPS-15-9570:~$ upower -i /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               SMP
  model:                DELL GPM0365
  serial:               1334
  power supply:         yes
  updated:              Mon 30 Nov 2020 08:49:03 PM CET (58 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    energy:              71.7288 Wh
    energy-empty:        0 Wh
    energy-full:         71.7288 Wh
    energy-full-design:  97.0026 Wh
    energy-rate:         0.0114 W
    voltage:             13.054 V
    percentage:          100%
    capacity:            73.9452%
    technology:          lithium-ion
    icon-name:          'battery-full-charged-symbolic'
```

**Comment by pepucho** [comment]
I'm sorry, I'm not longer running elementary on my laptop

**Comment by kvdz** [comment]
Hey, it should work with any Linux flavor. This data is valuable for us to understand all the different types of computers. If you have the chance to try the command in a Linux terminal that would be a great help.
