### ISSUE TITLE
Elementary OS drains the battery so fast.

### ISSUE THREAD

**Issue by thugianmotti** [elementary/wingpanel-indicator-power#139]
I just installed Elementary OS 1 day ago, I use it in parallel with Windows 10 operating system, For Windows 10, I use it in about 3h-5h, the battery capacity is reduced to less than 20%. But when I switched to Elementary OS, from 100% -> 88% in just 5 minutes, and in less than 1 hour, my laptop dropped below 20% battery capacity. I wonder what is the reason that Elementary OS consumes battery power so fast?

**Comment by jeremypw** [comment]
That sounds unusually heavy drainage. What apps were you running at the time and what work were you doing? Try running System Monitor (app) or htop (commandline) to see if there is a process that is continually consuming a high % of cpu in the background.

**Comment by andirsun** [comment]
Still facing the error in beta 6.0 ?

**Comment by cassidyjames** [comment]
This issue isn't really actionable nor relevant to the power indicator. A deeper investigation to what is draining power on your machine would be needed, but that's outside the scope of this repo.
