### ISSUE TITLE
When having similar devices, its hard to know which one has low battery

### ISSUE THREAD

**Issue by megatux** [elementary/wingpanel-indicator-power#144]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
Better description of device with low battery when more than one is present.
My user case: I have a wireless keyboard with touchpad and a wireless mouse. 
The indicator reports two mouse entries, one with low battery the other fully charged.
It's impossible to know which one needs charge.

(Sorry it's in Spanish)
![mouse-enery-issue](https://user-images.githubusercontent.com/850020/93031464-6d74e900-f601-11ea-8f96-adb16ed2f9fa.png)

**Describe the solution you'd like**
I'd suggest to display a diff. name for the touchpad one, or if both are recognize as "mouse" then add some extra hardware description in the label (or a hint with tooltip, etc)

**Comment by danrabbit** [comment]
It's possible we're defaulting to generic device types here because the vendor device names are very verbose or weird. But in this case where we have more then one we should probably use the vendor name to disambiguate

**Comment by kvdz** [comment]
@megatux  could you supply me with more internal information by entering the following commands in the terminal.

`upower -e`

example :
```
kay@kay-XPS-15-9570:~$ upower -e
/org/freedesktop/UPower/devices/line_power_AC
/org/freedesktop/UPower/devices/battery_BAT0
/org/freedesktop/UPower/devices/tablet_wacom_battery_0
/org/freedesktop/UPower/devices/DisplayDevice
```

Additional could add the following information as well?
`upower -i <Mouse path>`
And
` upower -i <keyboard path>`

Here is an example how to do this:
`upower -i /org/freedesktop/UPower/devices/battery_BAT0`

**Comment by megatux** [comment]
Hi!  sending the info. Just in case, I'm on a diff. laptop and a Manjaro Linux, but I guess the output of that program should be the same when using same external devices. 

```
$ upower -e
/org/freedesktop/UPower/devices/line_power_ACAD
/org/freedesktop/UPower/devices/battery_BAT1
/org/freedesktop/UPower/devices/mouse_hidpp_battery_0
/org/freedesktop/UPower/devices/mouse_hidpp_battery_1
/org/freedesktop/UPower/devices/DisplayDevice

$ upower -i /org/freedesktop/UPower/devices/mouse_hidpp_battery_0
  native-path:          hidpp_battery_0
  model:                Wireless Mouse M315/235/317
  serial:               4009-53-81-c6-1b
  power supply:         no
  updated:              mié 02 dic 2020 09:41:52 (51 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    battery-level:       full
    percentage:          100% (should be ignored)
    icon-name:          'battery-full-charged-symbolic'

$ upower -i /org/freedesktop/UPower/devices/mouse_hidpp_battery_1
  native-path:          hidpp_battery_1
  model:                Wireless All-in-One Keyboard TK820
  serial:               4102-b2-d6-e9-76
  power supply:         no
  updated:              mié 02 dic 2020 09:42:04 (43 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    battery-level:       normal
    percentage:          55% (should be ignored)
    icon-name:          'battery-low-symbolic'


$ upower -d
Device: /org/freedesktop/UPower/devices/line_power_ACAD
  native-path:          ACAD
  power supply:         yes
  updated:              mié 02 dic 2020 08:12:57 (5708 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              yes
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/battery_BAT1
  native-path:          BAT1
  vendor:               LGC
  model:                AP18E8M
  serial:               1523
  power supply:         yes
  updated:              mié 02 dic 2020 09:46:57 (68 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    energy:              55,9482 Wh
    energy-empty:        0 Wh
    energy-full:         56,4718 Wh
    energy-full-design:  57,4882 Wh
    energy-rate:         0,000485781 W
    voltage:             17,491 V
    percentage:          99%
    capacity:            98,0713%
    technology:          lithium-ion
    icon-name:          'battery-full-charged-symbolic'

Device: /org/freedesktop/UPower/devices/mouse_hidpp_battery_0
  native-path:          hidpp_battery_0
  model:                Wireless Mouse M315/235/317
  serial:               4009-53-81-c6-1b
  power supply:         no
  updated:              mié 02 dic 2020 09:47:52 (13 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    battery-level:       full
    percentage:          100% (should be ignored)
    icon-name:          'battery-full-charged-symbolic'

Device: /org/freedesktop/UPower/devices/mouse_hidpp_battery_1
  native-path:          hidpp_battery_1
  model:                Wireless All-in-One Keyboard TK820
  serial:               4102-b2-d6-e9-76
  power supply:         no
  updated:              mié 02 dic 2020 09:48:04 (1 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    battery-level:       normal
    percentage:          55% (should be ignored)
    icon-name:          'battery-low-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         yes
  updated:              mié 02 dic 2020 09:44:57 (188 seconds ago)
  has history:          no
  has statistics:       no
  battery
    present:             yes
    state:               fully-charged
    warning-level:       none
    energy:              55,9482 Wh
    energy-full:         56,4718 Wh
    energy-rate:         0,000485781 W
    percentage:          99%
    icon-name:          'battery-full-charged-symbolic'

Daemon:
  daemon-version:  0.99.11
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  yes
  critical-action: HybridSleep

```

Thanks

**Comment by kvdz** [comment]
@megatux  Thank you so much. indeed, another linux laptop with  same external devices is also good :+1: .

i am sad to hear you moved to another distro. Was this issue the main reason for switching distro?

**Comment by megatux** [comment]
Awesome! ... sure, a bit off-topic but mainly I wanted to use a rolling-release distro, with good tiling manager support (I use Manjaro-i3) because I prefer it for my development workflow. I found Gala a bit buggie, too. I used to use i3-regolith repos on top of Elementary with some issues. I still find elementaryos the best distro on UI/UX by far. I tried installing Pantheon AUR packages but had issues. Will retry later or maybe give the Nix packages a try. Also I was curious about the _Arch way_ :) . Finally, the reinstall-to-upgrade process of elementaryos is a big disappointment. Is this still true for 6.0?

**Comment by kvdz** [comment]
@megatux  thank you for sharing, I personally am not that familiar with i3-regolith repo or anything i3 related.
maybe @danrabbit  could answer your question if that is going to be supported in the future.

A question for @cassidyjames. Looking in the lookbook application for icons. i am not sure if we have a ican that has both mouse and keyboard in them.  like this:

![image](https://user-images.githubusercontent.com/4341214/101084631-88c31500-35ae-11eb-93e3-932c706f7a37.png)

From a UI standpoint it currently shows as a mouse. But we could make a difference here, because the type is reported as mouse but the model contains "keyboard" which we could filter and show a new icon.  That would help in this situation that you don't know which device it is. see original issue description.

**Comment by megatux** [comment]
Yeah, that's my external keyboard+touchpad, a very nice & solid peripheral.
It would be great if we can discover in a reliable way when there is a keyboard+pointing-dev or only a pointing-dev but that's bonus points :) , I'm ok with some different text in the label to differentiate each device.

**Comment by kvdz** [comment]
Issue is known upstream (https://gitlab.freedesktop.org/upower/upower/-/issues/139)

**Comment by kvdz** [comment]
I am closing this because changes are made that should fix this issue. I am not sure if it got released ye. But this will land in the next update or in next elementary OS release. Thank you for helping us create an awesome OS.
