### ISSUE TITLE
Two finger swipe/slide gesture to increase or decrease  the display brightness

### ISSUE THREAD

**Issue by CodeVault** [elementary/wingpanel-indicator-power#154]
## Problem

Add two finger swipe/slide  gesture to increase or decrease  the display brightness

## Proposal

Swiping gesture with two fingers on display brightness indicator.

**Comment by mr-islam** [comment]
Was just wishing for this feature as well — though rather than "two finger swipe" I think it's more accurate to say "on scroll", so mousewheels are also included in the phrasing

**Comment by jeremypw** [comment]
Makes sense that this indicator matches behaviour of the sound indicator, which changes the sound level on scrolling on the icon.

**Comment by TKivai** [comment]
Is it the intended behavior for touchpad users that brightness decreases when you swipe up and increases when you swipe down?
When using a mouse, brightness increases when scrolling up and vice versa (as expected) so it seems weird that it's the opposite when using a touchpad.

**Comment by mr-islam** [comment]
@TKivai, From what I quickly tested, the intended behavior is for brightness to increase on scroll up and decrease on scroll down.

Now, whether scroll up corresponds to swiping up or down depends on the "natural scrolling" option from touchpad settings. The brightness indicator respects this setting
