### ISSUE TITLE
"Show Percentage" on desktop PC shows 0%

### ISSUE THREAD

**Issue by Loreno10** [elementary/wingpanel-indicator-power#156]
As you can see in the screenshot, the widget shows "0%" when the "Show Percentage" option is selected:

![image](https://user-images.githubusercontent.com/10273406/102404419-0132c880-3fe8-11eb-95f6-7d0653fa185b.png)

I think it does not looks well. Probably PCs withotu a battery should not have the "Show Percentage" option at all.

I have 3 Bluetooth devices connected at the same time, I am not sure if they are the reason for this bug? I cannot really disconnect them, because then I will lose my mouse and keyboard :) (the 3rd device - AirPods - are not showing up in the battery widget unfortunately)

**Comment by kvdz** [comment]
There is a real issue here but other mentioned problems are a duplicat of https://github.com/elementary/wingpanel-indicator-power/issues/141  hence the label.

**Comment by kvdz** [comment]
Hi @Loreno10 , thank you for writing this up.

Could you post the output of this terminal command when this happens?

> upower -d

thank you very much

**Comment by Loreno10** [comment]
Sure, here's the result of `upower -d` (same as I posted in #174)

```sh
▶ upower -d
Device: /org/freedesktop/UPower/devices/keyboard_hid_34o88o5doc6oefod3_battery
  native-path:          hid-34:88:5d:c6:ef:d3-battery
  model:                Keyboard K380
  power supply:         no
  updated:              wto, 23 mar 2021, 08:00:39 (102 seconds ago)
  has history:          yes
  has statistics:       yes
  keyboard
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    percentage:          60%
    icon-name:          'battery-full-symbolic'

Device: /org/freedesktop/UPower/devices/mouse_hid_98ofdob4o7aoe5o31_battery
  native-path:          hid-98:fd:b4:7a:e5:31-battery
  model:                ThinkPad Bluetooth Laser Mouse
  power supply:         no
  updated:              wto, 23 mar 2021, 08:02:17 (4 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       critical
    percentage:          0%
    icon-name:          'battery-caution-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         no
  updated:              wto, 23 mar 2021, 07:57:41 (280 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       none
    icon-name:          'battery-missing-symbolic'

Daemon:
  daemon-version:  0.99.7
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  no
  critical-action: HybridSleep

```

**Comment by Loreno10** [comment]
@danrabbit The PR that you linked does not fix this problem. As I see, it just moves the switch to the top, whereas in the case of computers without battery there shouldn't even be an option to show battery percentage, unless there is some smart way of how to use it in a case like mine. Maybe showing the battery level of the device that has the lowest battery would be an improvement? That would at least be some valid information.
