### ISSUE TITLE
iPhone battery image is different than other batteries

### ISSUE THREAD

**Issue by Loreno10** [elementary/wingpanel-indicator-power#157]
# Problem

I noticed that the Batteries panel shows a different battery representation for iPhone, compared to my other devices. Only the iPhone one has a "lightning" symbol:

![image](https://user-images.githubusercontent.com/10273406/103208863-f4747580-4901-11eb-983a-8d218e2daaa1.png)

# System Info

eOS 5.1.7

**Comment by Loreno10** [comment]
Btw, the percentage shown by eOS is different than my actual battery level. In example, when eOS showed 51, iPhone showed 52. Then, when eOS showed 56, the phone showed 58.
It's totally unrelated, but let me know if I should create a separate bug for it.

**Comment by ryonakano** [comment]
> Only the iPhone one has a "lightning" symbol

I believe this is because your iPhone is charging via USB port of your PC. This should be intentional. Closing as "design conflicts"

> Btw, the percentage shown by eOS is different than my actual battery level. In example, when eOS showed 51, iPhone showed 52. Then, when eOS showed 56, the phone showed 58.
> It's totally unrelated, but let me know if I should create a separate bug for it.

Yeah you may want to create a separate bug for that

**Comment by Loreno10** [comment]
Hmm, didn't think about that. Makes sense!
