### ISSUE TITLE
Remove or disable brightness control when only external displays are connected

### ISSUE THREAD

**Issue by ayoungethan** [elementary/wingpanel-indicator-power#163]
In Hera 5.1.7

When only external displays are in use, the presence of a non-functioning brightness slider creates unnecessary confusion and clutter in the panel. Ref: https://elementaryos.stackexchange.com/questions/26429/is-brightness-control-supposed-to-work-on-desktop-systems-external-displays/26440#26440

Options for when only external displays are in-use:
1. Dim out/disable the slider
2. Hide or disable the indicator completely, as its only remaining functionality is to provide a shortcut to the power settings, much of which also have to do with brightness control.

**Comment by kvdz** [comment]
Hi @ayoungethan,  thank you for writing this feature request.
Could you help us by giving us more data?

could you give us the output of this terminal command

> upower -d

for when you use build in screen and when you only use external monitors.

**Comment by ayoungethan** [comment]
Hi Kay,

I don't have any built-in screens now (just a desktop computer). Also I
have uninstalled wingpanel-indicator-power, FYI, as all it seemed to
provide was the non-functional brightness slider. I can reinstall it if
needed.

Here is the output for external monitors:

$ upower -d
Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         no
  updated:              Wed 24 Mar 2021 11:32:17 AM CDT (2181 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       none
    icon-name:          'battery-missing-symbolic'

Daemon:
  daemon-version:  0.99.7
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  no
  critical-action: HybridSleep

**Comment by andirsun** [comment]
@ayoungethan I just create a PR to help with your feature request.

**Comment by jeremypw** [comment]
Needs UX team input on linked PR appearance.

**Comment by ayoungethan** [comment]
This issue is newly interesting to me after reading https://blog.elementary.io/user-interface-study-findings/ quoting:

> 81% use dark modes for at least one of health, accessibility, or environmental reasons—this really stands out to me! This 81% is using dark modes at least some of the time to address factors outside of their device like getting headaches, combating eye strain, or working in a darker office. This further cements in my mind that dark modes are a must have, and should be considered not just an aesthetic choice, but an accessibility concern.

Specifically as per https://github.com/elementary/switchboard-plug-power/issues/173#issuecomment-772097640 if brightness control is at all available for external displays via DDC/CI, then it strikes me as an accessibility issue to detect, expose and include that control for the same reasons as the dark theme above. Apparently most modern displays support it, and it's a limit of the OS...

Would this be a separate issue, ie, "Detect and expose brightness control for external displays that support it" as part 2, and this issue (disable brightness controls for displays that do not support it) is part 1 of the larger issue of offering full compatibility and accessibility in the OS for external displays?
