### ISSUE TITLE
Inaccurate tooltip on desktop

### ISSUE THREAD

**Issue by danrabbit** [elementary/wingpanel-indicator-power#172]
## What Happened

On desktop where there is no battery, we see the tooltip
```
Battery: 0%
Middle-click to toggle percentage
```

## Expected Behavior

Since there is no battery and no percentage, none of this information makes sense. We need a string to describe attached devices' batteries

**Comment by pongloongyeat** [comment]
Does this happen when you attach a battery powered device on the desktop?

**Comment by danrabbit** [comment]
Ah yeah this changed since I filed the report since now we get the device name and don't hardcode "battery". So I also get null null.

On desktop I've got a different icon since there is no backlight present :)

**Comment by jeremypw** [comment]
OK, that's good.  I can go ahead and propose a fix for the `(null): (null)`.  Can we assume that in this case the device is on "Line Power"?

**Comment by jeremypw** [comment]
I guess "Middle-click to toggle percentage" is irrelevant in this case too.

**Comment by danrabbit** [comment]
@jeremypw I'm not sure "line power" is a phrase that is commonly in use in US English, but I think the more important thing is that in this case the indicator isn't showing the power state of the computer as much as it is showing the battery level of peripherals or other attached charging devices

**Comment by jeremypw** [comment]
I said that because that phrase is used in the code and also, it turns out, is returned by the system as the name of the power supply device on my laptop when the battery is removed so that is what appears in the tooltip on my laptop with the linked PR. I haven't hard coded it.
