### ISSUE TITLE
Bluetooth mouse battery notifications - intrusive, needs a way to be disabled

### ISSUE THREAD

**Issue by Loreno10** [elementary/wingpanel-indicator-power#174]
Hi,
Recently I started getting these:
![battery ok](https://user-images.githubusercontent.com/10273406/111659140-4516b300-880d-11eb-9dfa-5d6066f23738.png)

At first, I thought that it's a cool feature, and I kinda liked it.
A week later, after getting this multiple times a day, I'm not such a huge fan anymore.

Well, the feature is cool, but there should be some switch to disable that. I know that the easiest solution would be to replace the battery, but I don't think that it's actually required. My mouse has a built-in indicator of low battery level, and it isn't even on yet. I'd wait till it discharges completely anyway.

**Comment by kvdz** [comment]
Hi Loreno,  thank you for taking the time to file this bug.

Just so you are aware, your are able in the notifications settings to turn them off by application.
Maybe that lifts the annoyment for in the mean time.

If you would be so kind if you could add the output of the following terminal command:

>  upower -d

This helps us to see what data the systems sees. This data is purely related to devices that are connected. for example a battery of a wireless mouse in this case.

**Comment by danrabbit** [comment]
I believe these notifications are sent by the power plugin for GNOME Settings Daemon. As far as I can tell, there are no options for disabling these notifications. We'd have to probably carry a patch against GSD or blacklist it in the notifications server to provide our own notifications

**Comment by Loreno10** [comment]
@kvdz Right, I didn't think about that. However, there doesn't seem to be an option for the battery-related stuff to be disabled. There's network, and that' about it from the things that can be found on the wing panel:
![image](https://user-images.githubusercontent.com/10273406/112106504-0cc8f900-8bae-11eb-947c-f96578bc313b.png)

Here's the result of `upower -d`:

```sh
▶ upower -d
Device: /org/freedesktop/UPower/devices/keyboard_hid_34o88o5doc6oefod3_battery
  native-path:          hid-34:88:5d:c6:ef:d3-battery
  model:                Keyboard K380
  power supply:         no
  updated:              wto, 23 mar 2021, 08:00:39 (102 seconds ago)
  has history:          yes
  has statistics:       yes
  keyboard
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    percentage:          60%
    icon-name:          'battery-full-symbolic'

Device: /org/freedesktop/UPower/devices/mouse_hid_98ofdob4o7aoe5o31_battery
  native-path:          hid-98:fd:b4:7a:e5:31-battery
  model:                ThinkPad Bluetooth Laser Mouse
  power supply:         no
  updated:              wto, 23 mar 2021, 08:02:17 (4 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       critical
    percentage:          0%
    icon-name:          'battery-caution-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         no
  updated:              wto, 23 mar 2021, 07:57:41 (280 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       none
    icon-name:          'battery-missing-symbolic'

Daemon:
  daemon-version:  0.99.7
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  no
  critical-action: HybridSleep
```

**Comment by kvdz** [comment]
@Loreno10  thank you for the additional information, sadly as @danrabbit  mentioned and you found out too. that there is no method to mute the notification.  On the other hand we trust on the information Upower and kernel drivers supply us. from what It is giving us the battery of you mouse is in critical discharge state. which means the battery  is almost out of power.

sadly i can not make see this as an issue for the Power indicator.  due to the fact that an other component is responsable for it.
There for i would like to redirect you to https://github.com/elementary/switchboard-plug-notifications and request for a feature to blacklist these notifications.  i created an issue for you (https://github.com/elementary/switchboard-plug-notifications/issues/77 )

closing this issue.
