### ISSUE TITLE
Incorrect Battery Percentage Shown

### ISSUE THREAD

**Issue by kdwk** [elementary/wingpanel-indicator-power#176]
## What Happened

When I plug in an iPad to my PC, the power indicator shows that the 'Computer' is charged to the battery percentage of the iPad.

![Screenshot from 2021-03-23 19-20-24](https://user-images.githubusercontent.com/39268094/112139096-5432a200-8c0d-11eb-9394-fde295fcdb44.png)
The iPad is charged to 42%, the computer is a desktop.

## Expected Behavior

The indicator should show that the iPad is charged to 42%

## Steps to Reproduce

1. Plug in an iPad/ iPhone to a desktop PC
2. Open wingpanel-indicator-power

## Platform Information

![Screenshot from 2021-03-23 19-26-55](https://user-images.githubusercontent.com/39268094/112139472-c2776480-8c0d-11eb-8492-0497967c0cd1.png)

**Comment by danrabbit** [comment]
Unlike that kid from the Apple commercial, it seems upower identifies this device as a computer! We should probably see if we can be clearer about it being an external device at the least and if there's a way we could try to identify that it is in fact a tablet

**Comment by kvdz** [comment]
@kdwk  i agree with @danrabbit , but i would like to have some more data.

when you plugin an ipad/iphone. could you open up a terminal and execute this command

> upower -d

could you post the output in here so we can see what the system thinks it is.

**Comment by kdwk** [comment]
Here's the output of `upower -d`

Device: /org/freedesktop/UPower/devices/mouse_dev_E8_1F_35_07_1C_29
  native-path:          /org/bluez/hci0/dev_E8_1F_35_07_1C_29
  model:                Designer Mouse
  serial:               E8:1F:35:07:1C:29
  power supply:         no
  updated:              Thursday, January 01, 1970 AM08:00:00 HKT (1616568510 seconds ago)
  has history:          yes
  has statistics:       no
  mouse
    present:             yes
    rechargeable:        no
    state:               unknown
    warning-level:       none
    percentage:          68%
    icon-name:          'battery-missing-symbolic'

Device: /org/freedesktop/UPower/devices/keyboard_dev_C3_32_8C_27_85_41
  native-path:          /org/bluez/hci0/dev_C3_32_8C_27_85_41
  model:                Designer Keyboard
  serial:               C3:32:8C:27:85:41
  power supply:         no
  updated:              Thursday, January 01, 1970 AM08:00:00 HKT (1616568510 seconds ago)
  has history:          yes
  has statistics:       no
  keyboard
    present:             yes
    rechargeable:        no
    state:               unknown
    warning-level:       none
    percentage:          69%
    icon-name:          'battery-missing-symbolic'

Device: /org/freedesktop/UPower/devices/computer_1_4
  native-path:          /sys/devices/pci0000:00/0000:00:14.0/usb1/1-4
  vendor:               Apple_Inc.
  model:                iPad
  serial:               12acee44f66ac10e9c529b7322213b5f74a0d8b9
  power supply:         no
  updated:              Wednesday, March 24, 2021 PM02:48:27 HKT (3 seconds ago)
  has history:          yes
  has statistics:       no
  computer
    warning-level:       none
    percentage:          53%
    icon-name:          'battery-good-charging-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         no
  updated:              Wednesday, March 24, 2021 PM02:28:04 HKT (1226 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       none
    icon-name:          'battery-missing-symbolic'

Daemon:
  daemon-version:  0.99.7
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  no
  critical-action: PowerOff

As you can see, the iPad is categorized as 'computer_1_4', but the model is correctly identified as 'iPad'

**Comment by kvdz** [comment]
Thank you. Currently we classify based on the device type which in this case is computer. But I think we could make it more smart to show ipad instead. What do you say @danrabbit ?

**Comment by danrabbit** [comment]
@kvdz yeah it would be nice if we could solve this upstream, but adding a special case to recognize iPad would probably be fine

**Comment by danrabbit** [comment]
Fixed in master :)
