### ISSUE TITLE
Differentiate between mouse and touchpad

### ISSUE THREAD

**Issue by JoseExposito** [elementary/wingpanel-indicator-power#186]
## Problem

When an external touchpad is connected it is recognized as a mouse:

![battery](https://user-images.githubusercontent.com/1335948/117335364-5db15a00-ae9b-11eb-9635-6a499e116c2f.png)

It can get even more confusing when also a mouse is connected.

## Proposal

Differentiate between mice and touchpads and show the right icon.

Niche feature request, I know :wink: 

## Prior Art

Could be similar to https://github.com/elementary/wingpanel-indicator-power/issues/144

**Comment by andirsun** [comment]
please paste command
``` upower -d ```

**Comment by JoseExposito** [comment]
The problem seems to be in a lower layer, that command prints "mouse". Closing the issue as it is out of the scope of the indicator.
