### ISSUE TITLE
Scroll direction feels backwards with Natural Scrolling

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-power#189]
## What Happened

Since fixing #154, you can scroll over the indicator icon to change brightness; however, on a touchpad with natural scrolling, the scroll direction feels inverted—especially because the volume indicator always has move-fingers-up to increase and down to decrease regardless of the natural scrolling setting.

## Expected Behavior

Moving your fingers up on the touchpad should increase brightness, down should decrease (regardless of Natural Scrolling setting)

## Steps to Reproduce

1. Ensure Natural Scrolling is enabled (it is by default)
2. Place the mouse cursor on top of the volume indicator and observe its behavior when you scroll your fingers up (increases volume) and down (decreases volume)
3. Do the same over the power indicator and observe how it is inverted.

## Platform Information

elementary OS 6 Early Access, up to date as of today

**Comment by jeremypw** [comment]
I note that the sound indicator already increases the volume with natural-scroll up.   However, Files and Photos scroll-zooming increases the icon size on natural-scroll *down*.  Is this an inconsistency?

**Comment by cassidyjames** [comment]
@jeremypw possibly, but I think it makes sense to focus this issue on the indicator scrolling as it's a more specific interaction. y instinct is that Photos and Files should treat zooming similarly to how it works with scrolling on the indicators, but that could be discussed separately on those apps.
