### ISSUE TITLE
Control brightness by scrolling

### ISSUE THREAD

**Issue by Djaler** [elementary/wingpanel-indicator-power#20]
I think, there should be able to control screen brightness by scrolling on power indicator, as it is now in sound indicator with volume control

**Comment by matzipan** [comment]
Furthermore, one of the problems I have right now when I use the scroll over the current slider is that it get sluggish. I suspect this is because it does recieves a smooth scroll message, and smooth scroll messages have a very high granularity.

**Comment by peteruithoven** [comment]
This should be implemented using a similar approach as the sound indicator, see: [handle_scroll](https://github.com/elementary/wingpanel-indicator-sound/blob/master/src/Indicator.vala#L341-L394).
 (since PR: https://github.com/elementary/wingpanel-indicator-sound/pull/81)

**Comment by jeremypw** [comment]
Fixed by #180
