### ISSUE TITLE
Implement horizontal scroll on icon

### ISSUE THREAD

**Issue by jeremypw** [elementary/wingpanel-indicator-power#201]
## Problem

Horizontal scrolling on the power icon has no effect.
## Proposal

Now that horizontal scroll on the sound icon has been implemented, it would be good for consistency to implement the same on the power icon.

## Prior Art

See wingpanel-indicator-sound.

**Comment by andirsun** [comment]
Sure!, let me work on this

**Comment by andirsun** [comment]
Done !
