### ISSUE TITLE
git master fails to compile with older vala versions due to syntax error

### ISSUE THREAD

**Issue by decathorpe** [elementary/wingpanel-indicator-power#202]
```
../src/Widgets/ScreenBrightness.vala:45.9-45.9: error: syntax error, expected identifier
        };
        ^
```

Looks like commit https://github.com/elementary/wingpanel-indicator-power/commit/ec10c486e72c4eb37c9f3c91b682f29ac5b116ae uses Vala syntax features (trailing comma in constructor arguments or something like that?) that's not supported on any but the most recent versions of Vala.

**Comment by ryonakano** [comment]
Nope, this breaks the build:

https://github.com/elementary/wingpanel-indicator-power/blob/ec10c486e72c4eb37c9f3c91b682f29ac5b116ae/src/Widgets/ScreenBrightness.vala#L44
