### ISSUE TITLE
Inaccurate battery level icons

### ISSUE THREAD

**Issue by ericpritchett** [elementary/wingpanel-indicator-power#239]
### What Happened?

Going from, for example, 60% power to 59% power left in your laptop battery switches the icon that looks like it goes from 75% to %50. The same thing occurs if your power is 90% the battery icon looks like it is 100%.

### Steps to Reproduce

Watch the range of the power icon and how the percentage of your laptop battery cooresponds to the icon. For example, 60% power to 59% power left in your laptop battery switches the icon that looks like it goes from 75% to %50 instead.

### Expected Behavior

The expected behavior should do one if not both of the following:

1. The power level should fall to whatever icon has the closet value to the indicated icon. For example 60% is closer to the 50% power icon and not 75% icon.
2. More icons should be added to better reflect the percentage. For example, if the battery icon has 10 pixels worth of "juice" (power level) then each icons should go down a pixel that represents 10% each. For example, 100%-95% should show a full battery, but 94%-86% should show a "90%" full battery icon.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by vjr** [comment]
@ericpritchett see https://github.com/elementary/wingpanel-indicator-power/pull/240#issuecomment-1345345731

**Comment by lenemter** [comment]
Fixed in #240.
