### ISSUE TITLE
is "Apps using lots of power" accurate?

### ISSUE THREAD

**Issue by farhatizakaria** [elementary/wingpanel-indicator-power#250]
### What Happened?

"Apps using lots of power" is a good feature to inform users about the power consomation, but sometimes is not accurate. For example "System Settings" and "Files" will not consume much power than Chrome or OBS obviously. I noticed also it depends on the window of an app is focused or not, to determine that app is using lots of power.

![Screenshot from 2023-08-17 01 11 18](https://github.com/elementary/wingpanel-indicator-power/assets/52662349/7ed8efa1-d6cb-452a-b6ae-26507f8161f9)

![Screenshot from 2023-08-17 01 20 47](https://github.com/elementary/wingpanel-indicator-power/assets/52662349/8fee549b-ff32-4639-8258-570498491c4e)

### Steps to Reproduce

1. Open any app that won't consume lots of power
2. Check power indicator
3. It shows that app is consuming lots of power 😆 

### Expected Behavior

Accuarte information about that app if it consumes lots of power

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

System:
```
  Host: Dell-Latitude Kernel: 6.2.0-26-generic x86_64 bits: 64
    Desktop: Pantheon Distro: elementary OS 7 Horus
Machine:
  Type: Laptop System: Dell product: Latitude E7450 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 0D8H72 v: A00 serial: <superuser required> UEFI: Dell
    v: A24 date: 04/11/2020
CPU:
  Info: dual core Intel Core i5-5300U [MT MCP] speed (MHz): avg: 823
    min/max: 500/2900
Graphics:
  Device-1: Intel HD Graphics 5500 driver: i915 v: kernel
  Device-2: Sunplus Innovation Integrated_Webcam_HD type: USB
    driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 resolution: 1366x768~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2)
    v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1
Network:
  Device-1: Intel Ethernet I218-LM driver: e1000e
  Device-2: Intel Wireless 7265 driver: iwlwifi
  Device-3: Intel Bluetooth wireless interface type: USB driver: btusb
Drives:
  Local Storage: total: 465.76 GiB used: 16.13 GiB (3.5%)
Info:
  Processes: 267 Uptime: 22m Memory: 7.62 GiB used: 2.85 GiB (37.4%)
  Shell: Bash inxi: 3.3.13
```

**Comment by danirabbit** [comment]
Closing since we removed this feature
