### ISSUE TITLE
Mouse battery indicator stuck at 50%

### ISSUE THREAD

**Issue by tradecraft1** [elementary/wingpanel-indicator-power#256]
### What Happened?

My rechargeable mouse always shows 50% charged regardless of its actual state of charge. 

### Steps to Reproduce

Clicked on the Power icon on Wingpanel
Mouse shows 50% charged always

### Expected Behavior

Wingpanel should show the actual status of the mouse battery charge

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Output from upower -d

Device: /org/freedesktop/UPower/devices/mouse_hidpp_battery_0
  native-path:          hidpp_battery_0
  model:                Performance MX
  serial:               ef-ff-72-ca
  power supply:         no
  updated:              Mon 11 Mar 2024 05:50:20 AM EDT (34 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    battery-level:       unknown
    percentage:          50% (should be ignored)
    icon-name:          'battery-full-charged-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         no
  updated:              Sun 10 Mar 2024 09:42:34 AM EDT (72500 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       none
    percentage:          0%
    icon-name:          ''

Daemon:
  daemon-version:  0.99.17
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  no
  critical-action: PowerOff
```

**Comment by danirabbit** [comment]
This is because the indicator currently doesn't handle coarse battery level reporting. There's an example of how we might handle that in this proposed branch: https://github.com/elementary/switchboard-plug-power/pull/253

**Comment by tradecraft1** [comment]
Thank you. I did notice something today. The power level does not change when the mouse is plugged in. When it is not plugged in it seems to have the right charge percentage. I am going to test some more things today.

**Comment by danirabbit** [comment]
@tradecraft1 that's okay this doesn't need any further information at the moment. If it still isn't working after coarse battery levels are implemented then we can see if there's something else going on, but I'm pretty confident that's the issue :)
