### ISSUE TITLE
Battery status goes to zero when plugging/unplugging cable

### ISSUE THREAD

**Issue by wout** [elementary/wingpanel-indicator-power#270]
### What Happened?

While plugging in or unplugging the power cable, the battery status temporarily goes to 0/critical for a few seconds:

![image](https://github.com/user-attachments/assets/2a6a4a20-9d52-4872-b60d-cfa46717a08c)

**UPDATE**:
The same thing happens every time a Bluetooth device is connected.

### Steps to Reproduce

1. With battery 100% charged, unplug the cable
2. Icon goes to 0/critical while percentage stays at 100%
3. After a few seconds, the correct icon appears again
4. Plug in the cable, icon goes to 0/critical again

### Expected Behavior

The icon should show the correct percentage

### OS Version

8.x (Early Access)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Hardware Info

```
         eeeeeeeeeeeeeeeee             wout@Framey
      eeeeeeeeeeeeeeeeeeeeeee          -----------
    eeeee  eeeeeeeeeeee   eeeee        OS: elementary OS circe 8 x86_64
  eeee   eeeee       eee     eeee      Host: Laptop (12th Gen Intel Core) (A8)
 eeee   eeee          eee     eeee     Kernel: Linux 6.8.0-48-generic
eee    eee            eee       eee    Uptime: 12 hours, 7 mins
eee   eee            eee        eee    Packages: 1811 (dpkg), 18 (flatpak-system), 18 (flatpak-user), 7 (sn)
ee    eee           eeee       eeee    Shell: bash 5.2.21
ee    eee         eeeee      eeeeee    Display (BOE095F): 3000x2000 @ 60 Hz in 13" [Built-in]
ee    eee       eeeee      eeeee ee    DE: Pantheon
eee   eeee   eeeeee      eeeee  eee    WM: Mutter(Gala) (X11)
eee    eeeeeeeeee     eeeeee    eee    Theme: Yaru [GTK3], io.elementary.stylesheet.blueberry [GTK4]
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee     Icons: Yaru [GTK3], elementary [GTK4]
  eeeeeeee eeeeeeeeeeee      eeee      Font: Inter (9pt) [GTK4]
    eeeee                 eeeee        Cursor: elementary
      eeeeeee         eeeeeee          Terminal: x-terminal-emulator
         eeeeeeeeeeeeeeeee             CPU: 12th Gen Intel(R) Core(TM) i7-1280P (20) @ 4.80 GHz
                                       GPU: Intel Iris Xe Graphics @ 1.45 GHz [Integrated]
                                       Memory: 7.24 GiB / 62.51 GiB (12%)
                                       Swap: 0 B / 3.80 GiB (0%)
                                       Disk (/): 70.54 GiB / 910.86 GiB (8%) - ext4
                                       Disk (/media/wout/1TB Framework): 168.41 GiB / 913.59 GiB (18%) - ex4
                                       Local IP (wlp166s0): 192.168.1.253/24
                                       Battery (Framewo): 93% (2 hours, 56 mins remaining) [Discharging]
                                       Locale: en_US.UTF-8
```

**Comment by TomiOhl** [comment]
Same here, but there is one more scenario. I have set a charging threshold to 85% (it's a firmware setting or similar on thinkpads). Now when I charge the laptop to that level, the battery icon changes to the red one with the warning triangle. Since I normally work with the laptop plugged in, I get to look at a critical battery symbol the whole day.

**Comment by candiedoperation** [comment]
When I plug in or unplug, I get this behavior for a few seconds. It exactly aligns with this issue so, +1

Here's another screenshot:
![image](https://github.com/user-attachments/assets/e0835ca8-9f25-48c9-a4cd-ac5c27f5f1a7)

**Comment by alainm23** [comment]
I just sent the fix, could you help me to check if it is fixed in your cases?
