### ISSUE TITLE
Latest update broke icon alignment

### ISSUE THREAD

**Issue by Tomires** [elementary/wingpanel-indicator-power#31]
The icon is now misaligned as per image.
![image](https://cloud.githubusercontent.com/assets/7209990/25590021/2169fd4c-2eaf-11e7-9cfc-99ba65764dfe.png)

**Comment by manV** [comment]
I can confirm this

**Comment by danrabbit** [comment]
Please don't make +1 comments, use the thumbs up reaction instead.

**Comment by tintou** [comment]
It's now fixed with current master
