### ISSUE TITLE
Hide users from the menu

### ISSUE THREAD

**Issue by robertsanseries** [elementary/wingpanel-indicator-power#36]
There is no way to hide when there are many users

![users](https://cloud.githubusercontent.com/assets/11967501/25768425/12b8ca5c-31da-11e7-86ad-4ba1e41f3076.png)

**Comment by danrabbit** [comment]
This is the the issue tracker for the power indicator. Please report issues for the session indicator here: https://github.com/elementary/wingpanel-indicator-session

Marking this report as "invalid" since it's not about the power indicator

**Comment by robertsanseries** [comment]
sorry, I'll pay more attention! 

Done! https://github.com/elementary/wingpanel-indicator-session/issues/15
