### ISSUE TITLE
Brightness indicator icon appears much bigger than the other icons

### ISSUE THREAD

**Issue by matzipan** [elementary/wingpanel-indicator-power#40]
![screenshot from 2017-05-13 22 32 59](https://cloud.githubusercontent.com/assets/317239/26036900/25425cae-38df-11e7-95fe-43280ba49ecd.png)

Using the daily icon set. Opening 24/brightness and symbolic/brightness icons doesn't reveal anything out of the ordinary, as the icons look as they should, with the <path> being only 15x15.

**Comment by danrabbit** [comment]
Closing since this is an icons issue and not an indicator issue
