### ISSUE TITLE
Double separator

### ISSUE THREAD

**Issue by markodp** [elementary/wingpanel-indicator-power#43]
![screenshot from 2017-05-28 19 11 49](https://cloud.githubusercontent.com/assets/805017/26530670/a8ecddc2-43d9-11e7-9bdc-ac7c203751dd.png)

**Comment by kvdz** [comment]
i think the par which shows the apps which uses lots of power are bank.  could you open it a couple of times after each other. this could show it.

**Comment by markodp** [comment]
No, it doesn't show it after. I am not sure if apps should be shown anyway, because this is from desktop pc not laptop. I am assuming power indicator is shown only because keyboard and mouse which have rechargeable batteries.

**Comment by kvdz** [comment]
oh your on a desktop that is help full information that can be the reason it is showing the 2 separators.
