### ISSUE TITLE
make notifications transient

### ISSUE THREAD

**Issue by snowparrot** [elementary/wingpanel-indicator-power#44]
Notifications about battery status ("You have 10 % left") wont be read 10 minutes later so they can be transient then they arent in the notification center.

**Comment by danrabbit** [comment]
At the moment we're relying on GNOME Settings Daemon for power status notifications. As far as I can tell, the notifications can't be disabled without disabling the whole of the power manager. So either we need to patch the GNOME power manager plugin or write our own power manager.

**Comment by kvdz** [comment]
@danrabbit  i don't think this is a reasonable feature request for the indicator. because of that and its age. i am closing this issue.
Correct me if you feel otherwise.
