### ISSUE TITLE
Brightness slider doesn't work on artful

### ISSUE THREAD

**Issue by danrabbit** [elementary/wingpanel-indicator-power#48]
It defaults to 0 and sliding it does nothing

**Comment by Philip-Scott** [comment]
Seems to be a problem with DBus properties and vala (as it always is when working with Dbus and vala :P) 

The interface in d-feet (`org.gnome.SettingsDaemon.Power.Screen`) is returning the correct values for brightness, but every time it's being called a 0 get's returned
