### ISSUE TITLE
Support smooth scrolling brightness change

### ISSUE THREAD

**Issue by matzipan** [elementary/wingpanel-indicator-power#58]
After #57 is closed, the indicator will finally have scroll on the indicator icon. However, neither the icon scroll neither the scroller scroll can handle smooth scrolling gracefully. Currently, #57 increments the brightness 10% for every scroll event, which means a small amount of smooth scroll can lead to a big change. 

To support smooth scrolling, the handler needs to check if the event is [smooth](https://valadoc.org/gdk-3.0/Gdk.ScrollDirection.html) and then change the brightness value with a value scaled by the [delta_y](https://valadoc.org/gdk-3.0/Gdk.EventScroll.delta_y.html)

**Comment by peteruithoven** [comment]
Looks like this is an issue on behavior of a rejected PR, let's close this an put all the scroll related requests in: https://github.com/elementary/wingpanel-indicator-power/issues/20
