### ISSUE TITLE
Power Settings link has background with rounded corners on 0.4.1 Loki

### ISSUE THREAD

**Issue by 4ugustin** [elementary/wingpanel-indicator-power#67]
It's only in Power indicator. See screenshot:

![Screenshot](https://i.imgur.com/YBypaqy.png)

**Comment by danrabbit** [comment]
Would you happen to be running the unstable daily PPA?

**Comment by augustin-b** [comment]
No, I'm just running f741c58 build.

**Comment by crmlt** [comment]
Why this happen on Loki? I've also tried latest stylesheet from git but it hasn't any effect...
