### ISSUE TITLE
Battery Indicator Showing on a Desktop PC

### ISSUE THREAD

**Issue by yufelipeto** [elementary/wingpanel-indicator-power#83]
Battery indicator is showing in a Desktop PC with no batteries.
![captura de tela de 2018-07-25 23 31 05](https://user-images.githubusercontent.com/33873038/43238067-e8ab28de-9062-11e8-9a1b-a76d0cc3e36e.png)
![captura de tela de 2018-07-25 23 32 58](https://user-images.githubusercontent.com/33873038/43238117-2b7fb06c-9063-11e8-833a-d885553d5ea1.png)

**Comment by danrabbit** [comment]
Thanks for you report! Are you experiencing this issue in Loki or Juno Beta? Also do you have any connected devices that do have a battery like a wireless mouse, keyboard, tablet, phone, UPS, etc?

**Comment by yufelipeto** [comment]
I'm experiencing this on Juno beta. I have a  Wireless Keyboard + Mouse via dongle. But I don't think it is what is showing up on the indicator because my wireless keyboard and mouse are powered by AA batteries, not rechargeable ones.

**Comment by cassidyjames** [comment]
@yufelipeto if those devices report a battery level (like most Logitech or Bluetooth devices), it will show in the panel. Something that could help, though, is if we put a mouse icon next to it or somehow make it more clear that this is coming from a mouse and not an internal battery.

**Comment by yufelipeto** [comment]
Well, I think have bug too because I'm using the same periferals and isn't show that icon anymore. My devices aren't bluetooth, they are wirelless connected via a proprietary frequency dongle. It appears and disappears randomly.

**Comment by kvdz** [comment]
@yufelipeto  could you supply me with more internal information by entering the following commands in the terminal.

`upower -e`

example :

```
kay@kay-XPS-15-9570:~$ upower -e
/org/freedesktop/UPower/devices/line_power_AC
/org/freedesktop/UPower/devices/battery_BAT0
/org/freedesktop/UPower/devices/tablet_wacom_battery_0
/org/freedesktop/UPower/devices/DisplayDevice

```

**Comment by kvdz** [comment]
I tried it on several desktop (different cpu's, old newer) i am not seeing this issue. i am leaning towards closing this. and waiting for some one who can give us the needed information to actually fix this issue.  unless @yufelipeto reacts in a couple months time.

**Comment by cassidyjames** [comment]
Yeah we now use a power icon instead of a battery icon when we have connected devices with batteries but the system itself does not have a battery. So this should be resolved.
