### ISSUE TITLE
Unable to scrub indicator

### ISSUE THREAD

**Issue by btd1337** [elementary/wingpanel-indicator-power#86]
![screenshot from 2018-08-02 13 54 52](https://user-images.githubusercontent.com/11943860/43598790-f27fa0fc-965b-11e8-843c-039dd96963d0.png)

**Comment by danrabbit** [comment]
Closing this issue since nothing is intended to happen when hovering indicators. This is not a bug

**Comment by btd1337** [comment]
@danrabbit look at this https://streamable.com/bx75o

**Comment by danrabbit** [comment]
Ah, so the issue is that you're unable to scrub over to reveal the indicator.

I can't actually reproduce this. It was likely fixed in master. Marking as "incomplete" until someone else can confirm

**Comment by cassidyjames** [comment]
I am also unable to reproduce this. Is this still an issue for you @btd1337?

**Comment by btd1337** [comment]
No, the error has already been fixed. Thank you!
