### ISSUE TITLE
Power indicator recognizes touchscreen

### ISSUE THREAD

**Issue by inputsh** [elementary/wingpanel-indicator-power#90]
Similar to #14, the indicator tries to "calculate" the battery of Wacom HID 5110, which is actually a [pen-supported touchscreen](https://patchwork.kernel.org/patch/10105647/) of Lenovo Yoga 920:

![screenshot from 2018-09-27 11 59 24 2x](https://user-images.githubusercontent.com/4890548/46138721-e62fde80-c24c-11e8-86b3-b8cba6610d7c.png)

@danrabbit I wonder if this issue applies to your Yoga or only on pen-supported ones? Maybe we could create some sort of a blacklist?

Apart from above mentioned #14, I couldn't find any other similar issues.

**Comment by cassidyjames** [comment]
I've also seen this on Dell laptops with touch displays. I'm not sure if it supported a pen, but I'll look it up!

**Comment by landswipe** [comment]
Definitely occurs on XPS 15 (9570) - running "upower -e" lists /org/freedesktop/UPower/devices/tablet_wacom_battery_0. 

Blacklist would be a good idea...

**Comment by kvdz** [comment]
Fixed by https://github.com/elementary/wingpanel-indicator-power/pull/151

closing this.
