### ISSUE TITLE
Kernel 4.18

### ISSUE THREAD

**Issue by junocomp** [elementary/wingpanel-indicator-power#94]
When updating Juno to kernel 4.18, the wingpanel freezes and it is not clickable. While debugging wingpanel I keep getting

`** (wingpanel:5727): DEBUG: 15:03:26.031: Indicator.vala:117: Icon changed to "battery-low-symbolic"
`
And it repeats forever. 

I've also installed elementary-desktop (daily) on Ubuntu 18.10 and I have the same issue.

The panel will come back to normality after removing wingpanel-indicator-power.

https://github.com/elementary/wingpanel/issues/175

**Comment by giovannicaligaris** [comment]
I still can't find a solution to for this. Here are some new errors I'm getting.

```
** (wingpanel:2648): DEBUG: 14:04:15.346: DeviceManager.vala:126: Device "/org/freedesktop/UPower/devices/battery_BAT0" registered
** (wingpanel:2648): DEBUG: 14:04:15.347: PopoverWidget.vala:50: show brightness slider
** (wingpanel:2648): DEBUG: 14:04:15.372: Monitor.vala:42: Initialising process monitor.
File '/proc/31857/cmdline' doesn't exist.
File '/proc/31858/cmdline' doesn't exist.
File '/proc/31859/cmdline' doesn't exist.
File '/proc/31860/cmdline' doesn't exist.
```

```
(wingpanel:2648): DEBUG: 14:04:24.048: Indicator.vala:117: Icon changed to "battery-low-symbolic"
File '/proc/4903/cmdline' doesn't exist.
```

```
(wingpanel:2648): DEBUG: 14:07:14.755: Indicator.vala:117: Icon changed to "battery-low-symbolic"
(wingpanel:2648): Gtk-CRITICAL **: 14:07:16.063: gtk_widget_get_allocation: assertion 'GTK_IS_WIDGET (widget)' failed
(wingpanel:2648): Gtk-CRITICAL **: 14:07:14.530: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by giovannicaligaris** [comment]
I think this is an issue with ASPM instead. When I add pcie_aspm=off acpi=off the wingpanel works but the power indicator can not detect the battery anymore. It shows a star/light icon instead of the battery symbol.
