### ISSUE TITLE
Unresponsive behavior since 1/1/2018

### ISSUE THREAD

**Issue by BenoitDuffez** [elementary/wingpanel-indicator-power#95]
I'm using Elementary OS 0.4.1 Loki. I wanted to have seconds and week numbers in the date indicator, so I cloned the `wingpanel-indicator-datetime` repo, made my edits and all was fine.

Now since 2018 (apparently, because it was working fine before my holidays until December 22nd), the whole wingpanel is unresponsive and very slow. When I `pkill wingpanel` it slowly reappears (like in 30 seconds) and it is very slow or even not responsive at all. For example right now the time shown is 10:05 but it is 10:07, so it's been stuck for at least 2 minutes.

I reverted my local `wingpanel-indicator-datetime` to `master` and installed again, it didn't work (though my edits are indeed gone).  
I also reverted to system defaults with `sudo apt install --reinstall wingpanel wingpanel-indicator-datetime` but it's still not working properly (even after killing it).

Am I the only one experimenting this? How can I at least revert to a proper default _working_ behavior, or better how can I run again my edited indicator without the wingpanel lagging like crazy?

**Comment by peteruithoven** [comment]
This might be related to: https://github.com/elementary/wingpanel-indicator-power/issues/15

**Comment by BenoitDuffez** [comment]
@peteruithoven almost sure it is indeed.

**Comment by kvdz** [comment]
checking if this issue is still present? could anyone confirm for Freya 5.1? 
if no response in 1 or 2 months i will close this issue as cannot reproduce.

**Comment by BenoitDuffez** [comment]
No it's fine now thanks.
