### ISSUE TITLE
When charging, "minutes" spelled wrong - currently spelled as "minuts"

### ISSUE THREAD

**Issue by Pankovas** [elementary/wingpanel-indicator-power#97]

**Comment by davidmhewitt** [comment]
Searching for "minuts" in the project only finds this result:
https://github.com/elementary/wingpanel-indicator-power/blob/3b889ea2a5d55d020807df3159cd8a61db784845/po/ca.po#L100

Are you using Catalan language? If so and "minuts" is the incorrect translation, then it will need to be corrected on Weblate:
https://l10n.elementary.io/projects/wingpanel/wingpanel-indicator-power/ca/

**Comment by Pankovas** [comment]
Many thanks. I'm not using Catalan (using English), so hopefully it's already been fixed as you suspect.

**Comment by davidmhewitt** [comment]
Thanks, I can confirm that this was corrected here: https://github.com/elementary/wingpanel-indicator-power/commit/627ab1aed10522a53d143d5f7e1573cc71bbbd41

We're just waiting on a new release of the package.

**Comment by Pankovas** [comment]
Thanks!
